### ISSUE TITLE
SVGs not displaying

### ISSUE THREAD

**Issue by shay328** [maithemewp/mai-galleries#4]
I have SVGs loaded in a Mai Gallery block. The images are not displaying on the visual block editor nor the frontend of the page. 

It's possible they're loaded and it just needs CSS to give some sizing since SVGs don't have a width on their own.

<img width="1621" alt="Screen Shot on 2023-01-05 at 18-03-02" src="https://user-images.githubusercontent.com/43424037/211375827-2aa04e3f-6bc1-4af1-a526-f2635be198e7.png">

**Comment by JiveDig** [comment]
Thanks @shay328.

Fixed via https://github.com/maithemewp/mai-galleries/commit/b28eb90b70ca509d2bac2e68d7231d082bba6fd7
